[package]
name = "tauri-plugin-serialplugin"
version = "2.0.0-rc.4"
description = "Access the current process of your Tauri application."
edition = "2021"
authors = ["Tauri Programme within The Commons Conservancy"]
license = "Apache-2.0 OR MIT"
rust-version = "1.70"
links = "tauri-plugin-serialplugin"

[package.metadata.docs.rs]
rustc-args = [ "--cfg", "docsrs" ]
rustdoc-args = [ "--cfg", "docsrs" ]

[build-dependencies]
tauri-plugin = { version = "2.0.0-rc.12", features = [ "build" ] }

[dependencies]
serialport = "4.5.1"
tauri = "2.0.0-rc.15"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"